### ISSUE TITLE
[Mermaid] Uncaught (in promise) TypeError: mermaid.initialize is not a function

### ISSUE THREAD

**Issue by mrdrivingduck** [Renovamen/vuepress-theme-gungnir#35] opened 2022-02-27 09:39 UTC
vuepress-plugin-mermaid 2.0.0-alpha.15:

![1645954561(1)](https://user-images.githubusercontent.com/32560442/155877009-9b38208b-e95a-4100-a81e-2f72ba27e715.png)

My config looks like:

![image](https://user-images.githubusercontent.com/32560442/155877039-fb71d33e-eeec-4036-892b-3a44deed7ea5.png)

And I used your demo:

![image](https://user-images.githubusercontent.com/32560442/155877072-f23a4451-48ea-4197-a90e-9ed82b5b12fd.png)

Finally it shows like:

![image](https://user-images.githubusercontent.com/32560442/155877088-e5de0be4-ed5d-48d8-b066-bb10cee8ba0d.png)

What's the problem I'm facing to? Anyone can help?

**Comment by Renovamen** [comment] 2022-02-28 00:49
It's a bug caused by Mermaid's recent breaking changes. Fixed in 2.0.0-alpha.16. Thanks!

**Comment by mrdrivingduck** [comment] 2022-02-28 01:57
Appreciate your help! Your theme and plugin is great! ❤️

Problem solved.

**Closed as completed** 2022-02-28 17:25 UTC
