### ISSUE TITLE
perf: Blog website SEO

### ISSUE THREAD

**Issue by Zhengqbbb** [Renovamen/vuepress-theme-gungnir#28] opened 2022-01-24 07:23 UTC
# Current：
Apart from the docs page, link Home page(posts link), Tags page ... website SEO is not well.
# Affect:
- spider not working 
- the website cannot be included
# Analyze
Maybe it is use many v-for options data render page
# Other
Tags page router handle maybe have problems. You can try refresh in [Tags page](https://v2-vuepress-theme-gungnir.vercel.app/tags/).it will enter Home page.But Tags page of my website is 404. it will also make spider not working.

# Problem Description
![image](https://user-images.githubusercontent.com/40693636/150738961-28ed62ac-acfa-46d5-9ec2-5d536b1b49b5.png)

**Comment by Renovamen** [comment] 2022-01-25 04:23
Hi, thank you for your advice! You are right, SEO of this theme is poor as for now, I'll improve it once I have time.

Issues occuring when refreshing tags page (as well as pagination page like `/page/2/`) are caused by using `addRoute` to add dynamic routes. They should be fixed in https://github.com/Renovamen/vuepress-theme-gungnir/commit/fd5d6ca47d860f157f4a26805e3dcb145ae90eac by pre-rendering pages manully instead of using dynamic routes (see [here](https://github.com/Renovamen/vuepress-theme-gungnir/commit/fd5d6ca47d860f157f4a26805e3dcb145ae90eac#diff-97d78eea0a6ba157b3cdb606c7a3de8281d9fb79c043fe005c21d7a649265370)). Try refreshing [this page](https://v2-vuepress-theme-gungnir.vercel.app/tags/tag%20with%20space/). I guess this way would also be more friendly to SEO. 

However it's just a workaroud, the implementation is not elegant enough. It should be much better after [vuepress-plugin-blog](https://github.com/vuepress/vuepress-plugin-blog) supporting VuePress 2.

**Comment by Zhengqbbb** [comment] 2022-01-25 04:35
> Hi, thank you for your advice! You are right, SEO of this theme is poor as for now, I'll improve it once I have time.
> 
> Issues occuring when refreshing tags page (as well as pagination page like `/page/2/`) are caused by using `addRoute` to add dynamic routes. They should be fixed in [fd5d6ca](https://github.com/Renovamen/vuepress-theme-gungnir/commit/fd5d6ca47d860f157f4a26805e3dcb145ae90eac) by pre-rendering pages manully instead of using dynamic routes (see [here](https://github.com/Renovamen/vuepress-theme-gungnir/commit/fd5d6ca47d860f157f4a26805e3dcb145ae90eac#diff-97d78eea0a6ba157b3cdb606c7a3de8281d9fb79c043fe005c21d7a649265370)). Try refreshing [this page](https://v2-vuepress-theme-gungnir.vercel.app/tags/tag%20with%20space/). I guess this way would also be more friendly to SEO.
> 
> However it's just a workaroud, the implementation is not elegant enough. It should be much better after [vuepress-plugin-blog](https://github.com/vuepress/vuepress-plugin-blog) supporting VuePress 2.

Nice !
Yes, I also found out that the use of plugin blogs, whether they support the official library , scalability, the frequency of bugs and SEO will be well. I will also continue to pay attention, but I have too little time now. I will wait until vacation I have time to make changes together. Maybe you can create a [Discord](https://discord.com/) Channel([Vuepress official](https://discord.gg/bYhCj847) also has a discussion group), maybe you can have more discussions

**Comment by Renovamen** [comment] 2022-01-25 04:42
> # Analyze
> Maybe it is use many v-for options data render page
> 
> # Problem Description
> ![image](https://user-images.githubusercontent.com/40693636/150738961-28ed62ac-acfa-46d5-9ec2-5d536b1b49b5.png)

However, I think it's still hard for a spider to reach post titles from home page (or tags page) even after we improving the SEO? Using v-for to render post list is almost inevitable.

But I can try to inject more information of a page (title, description, author, etc.) to HTML meta header to improve SEO.

**Comment by Renovamen** [comment] 2022-01-25 05:03
> Maybe you can create a [Discord](https://discord.com/) Channel

Thanks for your suggestion. I don't think I have time to maintain a channel currently. I'll consider it later 😂

**Comment by Zhengqbbb** [comment] 2022-01-25 05:10
> Thanks for your suggestion. I don't think I have time to maintain a channel currently. I'll consider it later 😂

Well~ you can check your gmail.I have other repo request🤣

**Closed as completed** 2022-01-25 05:11 UTC
Labels: bug, enhancement
